{
  config,
  pkgs,
  lib,
  aiHarnessModelProfile,
  ...
}:

let
  yamlFormat = pkgs.formats.yaml { };
  mkYaml = name: attrs: yamlFormat.generate name attrs;

  # Model profiles — shared with pi.nix, opencode.nix
  # Change aiHarnessModelProfile in flake.nix → all harnesses update.
  models = import ./model-profiles.nix { profileName = aiHarnessModelProfile; };

  # Peon extension (lifecycle sounds via ~/.openpeon/ sound packs)
  enablePeonExtension = false;

in
{
  home.file = {

    # ═══════════════════════════════════════════════════════════════════
    # ~/.omp/agent/config.yml  (managed by Nix)
    # ═══════════════════════════════════════════════════════════════════
    #
    # NOTE: This file is a read-only Nix store symlink.
    # Changes via /settings inside omp are silently overwritten on rebuild.
    # Edit this file and run darwin-rebuild switch to persist.
    #
    # Full settings reference: omp config list
    #
    ".omp/agent/config.yml" = {
      source = mkYaml "omp-config.yml" {

        # ── appearance ──────────────────────────────────────────────
        theme = {
          dark = "dark-nord";
          light = "light-tokyo-night";
        };
        symbolPreset = "nerd";
        colorBlindMode = false;
        statusLine = {
          preset = "nerd";
          separator = "powerline";
          sessionAccent = true;
          showHookStatus = true;
        };
        display = {
          shimmer = "kitt";
          showTokenUsage = true;
          tabWidth = 3;
        };
        showHardwareCursor = true;
        clearOnShrink = false;

        # ── interaction ─────────────────────────────────────────────
        autoResume = true;
        steeringMode = "one-at-a-time";
        followUpMode = "one-at-a-time";
        interruptMode = "immediate";
        doubleEscapeAction = "tree";
        loop = {
          mode = "prompt";
        };
        treeFilterMode = "default";
        stt = {
          enabled = false;
        };

        # ── model ───────────────────────────────────────────────────
        defaultThinkingLevel = "high";
        hideThinkingBlock = false;
        repeatToolDescriptions = false;

        # ── editing ─────────────────────────────────────────────────
        edit = {
          mode = "hashline";
          fuzzyMatch = true;
          fuzzyThreshold = 0.95;
          hashlineAutoDropPureInsertDuplicates = false;
          blockAutoGenerated = true;
        };
        readLineNumbers = false;
        readHashLines = true;
        read = {
          defaultLimit = 300;
        };

        # ── lsp ─────────────────────────────────────────────────────
        lsp = {
          enabled = true;
          formatOnWrite = false;
          diagnosticsOnWrite = true;
          diagnosticsOnEdit = false;
        };

        # ── tools ───────────────────────────────────────────────────
        tools = {
          discoveryMode = "mcp-only";
          intentTracing = true;
        };
        find = {
          enabled = true;
        };
        search = {
          enabled = true;
        };
        calc = {
          enabled = true;
        };
        astGrep = {
          enabled = true;
        };
        astEdit = {
          enabled = true;
        };
        irc = {
          enabled = true;
        };
        debug = {
          enabled = true;
        };
        fetch = {
          enabled = true;
        };
        recipe = {
          enabled = true;
        };
        renderMermaid = {
          enabled = true;
        };
        inspect_image = {
          enabled = true;
        };
        github = {
          enabled = true;
        };
        web_search = {
          enabled = true;
        };
        browser = {
          enabled = true;
        };

        # ── mcp ─────────────────────────────────────────────────────
        mcp = {
          enableProjectConfig = true;
          discoveryMode = true;
          notifications = true;
        };

        # ── memory ──────────────────────────────────────────────────
        memory = {
          backend = "hindsight";
        };
        hindsight = {
          enabled = true;
          scoping = "per-project";
          autoRecall = true;
          autoRetain = true;
          retainMode = "full-session";
          bankMission = "A staff engineer using Oh My Pi (omp) for software development, architecture, design, code review, debugging, devops, document management, and general productivity tasks.";
        };
        branchSummary = {
          enabled = false;
        };
        secrets = {
          enabled = true;
        };

        # ── session ─────────────────────────────────────────────────
        compaction = {
          enabled = true;
          strategy = "context-full";
          reserveTokens = 16384;
          keepRecentTokens = 20000;
          autoContinue = true;
        };
        retry = {
          enabled = true;
          maxRetries = 3;
          baseDelayMs = 2000;
        };

        # ── plugins & marketplace ───────────────────────────────────
        plugins = {
          enabled = true;
          autoUpdate = false;
        };
        marketplace = {
          autoUpdate = "notify";
        };

        # ── commands & skills ───────────────────────────────────────
        commands = {
          enableClaudeProject = false;
          enableClaudeUser = false;
        };

        # ── todo ────────────────────────────────────────────────────
        todo = {
          enabled = true;
          eager = false;
          reminders = true;
        };

        # ── tasks ───────────────────────────────────────────────────
        task = {
          isolation = {
            mode = "auto";
            merge = "patch";
            commits = "ai";
          };
          eager = true;
          simple = "default";
        };

        # ── providers ───────────────────────────────────────────────
        providers = {
          webSearch = "auto";
          image = "auto";
        };
        exa = {
          enabled = true;
          enableSearch = true;
          enableResearcher = true;
          enableWebsets = true;
        };

        # ── model roles ─────────────────────────────────────────────
        modelRoles = {
          default = models.primary;
          inherit (models) fast plan;
          slow = models.plan;
          smol = models.fast;
          task = models.fast;
          commit = models.fast;
        };
      };
      force = true;
    };

    # ── Stream rules ────────────────────────────────────────────────
    # Rules activate on violation only — no permanent context tax.
    ".omp/agent/rules/guardrails.md".source = ./oh-my-pi/rules/guardrails.md;
    ".omp/agent/rules/pkg-mgr-auth.md".source = ./oh-my-pi/rules/pkg-mgr-auth.md;

    ".omp/agent/rules/research-protocol.md".source = ./oh-my-pi/rules/research-protocol.md;

    # ── Extensions ──────────────────────────────────────────────────
    # Custom omp extensions for lifecycle hooks.
    ".omp/agent/extensions/peon.ts" = lib.mkIf enablePeonExtension {
      source = ./oh-my-pi/extensions/peon.ts;
    };

    # ═══════════════════════════════════════════════════════════════════
    # ~/.omp/agent/mcp.json  (seed reference managed by Nix)
    # ═══════════════════════════════════════════════════════════════════
    #
    # Nix writes the reference file with base server entries. The post-nix
    # script (setup-post-nix.sh omp-oauth) merges it into the writable
    # mcp.json, resolves !op read secrets, and OMP's /mcp reauth adds
    # auth/oauth configs that survive future rebuilds.
    #
    ".omp/agent/mcp.json.reference" = {
      text = builtins.toJSON {
        mcpServers = {
          docker-mcp = {
            command = "docker";
            args = [
              "mcp"
              "gateway"
              "run"
            ];
          };
          context7 = {
            type = "http";
            url = "https://mcp.context7.com/mcp";
            env = {
              CONTEXT7_API_KEY = "!op read op://Private/context7/api-keys/opencode";
            };
          };
          qmd = {
            command = "qmd";
            args = [ "mcp" ];
          };
          Atlassian = {
            type = "http";
            url = "!op read op://Private/mcp-info/mcp-atlassian-url";
          };
          Backstage = {
            type = "http";
            url = "!op read op://Private/mcp-info/mcp-backstage-url";
          };
          Buildkite = {
            type = "http";
            url = "!op read op://Private/mcp-info/buildkite-mcp-url";
            headers = {
              X-Buildkite-Toolsets = "!op read op://Private/mcp-info/buildkite-mcp-toolsets";
            };
          };
          GitHub = {
            type = "http";
            url = "!op read op://Private/mcp-info/mcp-github-url";
          };
          Glean = {
            type = "http";
            url = "!op read op://Private/mcp-info/mcp-glean-url";
          };
          Figma = {
            type = "http";
            url = "!op read op://Private/mcp-info/mcp-figma-url";
          };
          Datadog = {
            type = "http";
            url = "!op read op://Private/mcp-info/datadog-mcp-url";
            headers = {
              DD-SITE = "!op read op://Private/mcp-info/datadog-mcp-site";
              DD-API-KEY = "!op read op://Private/mcp-info/datadog-mcp-dd-api-key";
              DD-APPLICATION-KEY = "!op read op://Private/mcp-info/datadog-mcp-dd-application-key";
            };
          };
          context-mode = {
            command = "context-mode";
          };
        };
      };
      force = true;
    };
  };
}
