{
  config,
  pkgs,
  aiHarnessModelProfile,
  ...
}:

let
  yamlFormat = pkgs.formats.yaml { };
  mkYaml = name: attrs: yamlFormat.generate name attrs;

  # Model profiles — shared with pi.nix, opencode.nix
  # Change aiHarnessModelProfile in flake.nix → all harnesses update.
  models = import ./model-profiles.nix { profileName = aiHarnessModelProfile; };

in
{
  home.file = {

    # ═══════════════════════════════════════════════════════════════════
    # ~/.omp/agent/config.yml  (managed by Nix)
    # ═══════════════════════════════════════════════════════════════════
    #
    # NOTE: This file is a read-only Nix store symlink.
    # Changes via /settings inside omp are silently overwritten on rebuild.
    # Edit this file and run darwin-rebuild switch to persist.
    #
    # Full settings reference: omp config list
    #
    ".omp/agent/config.yml" = {
      source = mkYaml "omp-config.yml" {

        # ── appearance ──────────────────────────────────────────────
        theme = {
          dark = "dark-nord";
          light = "light-tokyo-night";
        };
        symbolPreset = "nerd";
        colorBlindMode = false;
        statusLine = {
          preset = "nerd";
          separator = "powerline";
          sessionAccent = true;
          showHookStatus = true;
        };
        display = {
          shimmer = "kitt";
          showTokenUsage = true;
          tabWidth = 3;
        };
        showHardwareCursor = true;
        clearOnShrink = false;

        # ── interaction ─────────────────────────────────────────────
        autoResume = true;
        steeringMode = "one-at-a-time";
        followUpMode = "one-at-a-time";
        interruptMode = "immediate";
        doubleEscapeAction = "tree";
        loop = {
          mode = "prompt";
        };
        treeFilterMode = "default";
        stt = {
          enabled = false;
        };

        # ── model ───────────────────────────────────────────────────
        defaultThinkingLevel = "high";
        hideThinkingBlock = false;
        repeatToolDescriptions = false;

        # ── editing ─────────────────────────────────────────────────
        edit = {
          mode = "hashline";
          fuzzyMatch = true;
          fuzzyThreshold = 0.95;
          hashlineAutoDropPureInsertDuplicates = false;
          blockAutoGenerated = true;
        };
        readLineNumbers = false;
        readHashLines = true;
        read = {
          defaultLimit = 300;
        };

        # ── lsp ─────────────────────────────────────────────────────
        lsp = {
          enabled = true;
          formatOnWrite = false;
          diagnosticsOnWrite = true;
          diagnosticsOnEdit = false;
        };

        # ── tools ───────────────────────────────────────────────────
        tools = {
          discoveryMode = "mcp-only";
          intentTracing = true;
        };
        find = {
          enabled = true;
        };
        search = {
          enabled = true;
        };
        calc = {
          enabled = true;
        };
        astGrep = {
          enabled = true;
        };
        astEdit = {
          enabled = true;
        };
        irc = {
          enabled = true;
        };
        debug = {
          enabled = true;
        };
        fetch = {
          enabled = true;
        };
        recipe = {
          enabled = true;
        };
        renderMermaid = {
          enabled = true;
        };
        inspect_image = {
          enabled = true;
        };
        github = {
          enabled = true;
        };
        web_search = {
          enabled = true;
        };
        browser = {
          enabled = true;
        };

        # ── mcp ─────────────────────────────────────────────────────
        mcp = {
          enableProjectConfig = true;
          discoveryMode = true;
          notifications = true;
        };

        # ── memory ──────────────────────────────────────────────────
        memory = {
          backend = "hindsight";
        };
        hindsight = {
          enabled = true;
          scoping = "per-project";
          autoRecall = true;
          autoRetain = true;
          retainMode = "full-session";
        };
        branchSummary = {
          enabled = false;
        };
        secrets = {
          enabled = true;
        };

        # ── session ─────────────────────────────────────────────────
        compaction = {
          enabled = true;
          strategy = "context-full";
          reserveTokens = 16384;
          keepRecentTokens = 20000;
          autoContinue = true;
        };
        retry = {
          enabled = true;
          maxRetries = 3;
          baseDelayMs = 2000;
        };

        # ── plugins & marketplace ───────────────────────────────────
        plugins = {
          enabled = true;
          autoUpdate = false;
        };
        marketplace = {
          autoUpdate = "notify";
        };

        # ── commands & skills ───────────────────────────────────────
        commands = {
          enableClaudeProject = false;
          enableClaudeUser = false;
        };

        # ── todo ────────────────────────────────────────────────────
        todo = {
          enabled = true;
          eager = false;
          reminders = true;
        };

        # ── tasks ───────────────────────────────────────────────────
        task = {
          isolation = {
            mode = "auto";
            merge = "patch";
            commits = "ai";
          };
          eager = true;
          simple = "default";
        };

        # ── providers ───────────────────────────────────────────────
        providers = {
          webSearch = "auto";
          image = "auto";
        };
        exa = {
          enabled = true;
          enableSearch = true;
          enableResearcher = true;
          enableWebsets = true;
        };

        # ── model roles ─────────────────────────────────────────────
        modelRoles = {
          default = models.primary;
          inherit (models) fast plan;
          slow = models.plan;
          smol = models.fast;
          task = models.fast;
          commit = models.fast;
        };
      };
      force = true;
    };

    # ── Stream rules ────────────────────────────────────────────────
    # Rules activate on violation only — no permanent context tax.
    ".omp/agent/rules/guardrails.md".source = ./oh-my-pi/rules/guardrails.md;
    ".omp/agent/rules/pkg-mgr-auth.md".source = ./oh-my-pi/rules/pkg-mgr-auth.md;

    # ── OMP-native MCP servers: ~/.omp/agent/mcp.json ────────────────
    # MCP servers configured elsewhere (Claude, Cursor, etc.) are auto-discovered
    # by omp — no config needed here. This file only contains omp-native additions.
    #
    # Schema: packages/coding-agent/src/config/mcp-schema.json
    # Values starting with ! are resolved as shell commands at runtime.
    #
    ".omp/agent/mcp.json" = {
      text = builtins.toJSON {
        mcpServers = {
          docker-mcp = {
            command = "docker";
            args = [
              "mcp"
              "gateway"
              "run"
            ];
          };
          context7 = {
            url = "https://mcp.context7.com/mcp";
            env = {
              CONTEXT7_API_KEY = "!op read op://Private/wqnec2ehppfchca6xpmbvp6xem/api\ keys/opencode";
            };
          };
          qmd = {
            command = "qmd";
            args = [ "mcp" ];
          };
          open-pencil = {
            command = "bun";
            args = [
              "${config.home.homeDirectory}/.bun/bin/openpencil-mcp"
            ];
          };
        };
      };
      force = true;
    };
  };
}
